import React, {useCallback} from "react"

import {Button, Flex, Text} from "components/atoms"
import {TemplateA} from "components/templates/TemplateA"
import Head from "next/head"
import {signOut} from "next-auth/client"

const Setting:React.FunctionComponent = () => {

  const onClickSignOut  = useCallback(()=>{
    signOut({callbackUrl: "/"})  
  },[])

  return (
    <TemplateA>
      <Head>
        <title>Library of W</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex>
        <Button onClick={onClickSignOut}>Sign Out</Button>
      </Flex>
      
    </TemplateA>
  )
}

export default Setting;
