import React from "react"

import {Flex, Text} from "components/atoms"
import {TemplateA} from "components/templates/TemplateA"
import Head from "next/head"
import Image from "next/image"

export default function Home() {
  return (
    <TemplateA>
      <Head>
        <title>Library of W</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex>
        <Text>{"Library of W"}</Text>
      </Flex>
      
    </TemplateA>
  )
}
